trigger:
  - dev

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies' 

- script: |
    git config --global user.email "pipeline@azure.com"
    git config --global user.name "Pipeline"
    git config --global credential.helper store
    git config --global http.extraheader "AUTHORIZATION: basic $(echo -n git:$(GIT_TOKEN) | base64)"
        
  env:
    GIT_TOKEN: $(GIT_TOKEN)
  displayName: 'Authorization, switch branch and pull'

- script: |
    sphinx-apidoc -o sphinx_test/docs sphinx_test/src    
  displayName: 'Parse comments to REST files'

- script: |
    cd sphinx_test/docs
    make clean
    make html
    pwd
  displayName: 'Generate HTML documents'

- script: |  

    git add --all
    git commit -m "New edits in repo [skip ci]"

  env:
    GIT_TOKEN: $(GIT_TOKEN)
  displayName: 'Commit and Push changes to dev branch'

- script: |
    git fetch 
    git checkout main
    git pull origin main --rebase  
    git merge dev -m "Merging changes from dev to main [skip ci]"
    git push origin main
  displayName: 'Merge dev into main and push'
  env:
    GIT_TOKEN: $(GIT_TOKEN)