trigger:
- main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    sphinx-apidoc -o sphinx_test/docs sphinx_test/src    
  displayName: 'Parse comments to REST files'

- script: |
    cd sphinx_test/docs
    make clean
    make html
    pwd
  displayName: 'Generate HTML documents'

- script: |
    git checkout main  
    git pull
    git add *
    git commit -m "New edits en repo"
    git push origin main

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/vsts/work/1/s/sphinx_test/docs/_build/html'
    artifact: 'HTML'
    publishLocation: 'pipeline'
